"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:
[1, 2, 3, 5, 8, 13, 21, 34, 55, 89]
By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.</p>

"""
# sum of even-valued fib nums up to fib_limit
def problem2(fib_limit):
    num1 = 1
    num2 = 2
    fib_nums = [num1, num2]

    while num2 < fib_limit:
        temp = num1 + num2
        num1 = num2
        num2 = temp
        fib_nums.append(num2)
    
    fib_nums = fib_nums[1:] # remove 1 being an odd num
    even_nums = [num for num in fib_nums if num % 2 == 0 and num < fib_limit]
    sum_even_nums = sum(even_nums)

    print(sum_even_nums)
    return sum_even_nums

limit = 4000000
problem2(limit)